In [43]:
# Error 1: dependencies not imported
import pandas as pd

In [18]:
# Create a reference to the CSV and import it into a Pandas DataFrame

# Original Code
# Error 2: not setting "Read" data as new dataframe before printing
# csv_path = "EclipseBugs.csv"
# pd.read_csv(csv_path)

# Solution
bug_path = "EclipseBugs.csv"
eclipse_df=pd.read_csv(bug_path)
eclipse_df.head()

,Bug ID,Product,Component,Assignee,Status,Resolution,Summary,Changed,Assignee Real Name,Classification,...,Number of Comments,Opened,OS,Priority,Reporter,Reporter Real Name,Severity,Target Milestone,Version,Votes
0,3638,JDT,UI,aeschli,VERIFIED,FIXED,Package Viewer: order resource folders before ...,1/17/2002 7:28,Martin Aeschlimann,Eclipse,...,3,10/10/2001 22:58,Windows NT,P1,aeschli,Martin Aeschlimann,major,---,2,0
1,3854,JDT,UI,aeschli,VERIFIED,FIXED,Wrong execution's classpath. (1GEY0W0),1/18/2002 4:02,Martin Aeschlimann,Eclipse,...,5,10/10/2001 23:01,Windows NT,P1,david_audel,David Audel,normal,---,2,0
2,4188,JDT,UI,aeschli,VERIFIED,FIXED,type hierachy - typo (1GJW2XJ),1/28/2002 3:12,Martin Aeschlimann,Eclipse,...,3,10/10/2001 23:07,Windows 2000,P1,erich_gamma,Erich Gamma,normal,---,2,0
3,5115,JDT,Debug,aeschli,VERIFIED,FIXED,Workspace source locator fails with mulitple p...,11/13/2001 10:11,Martin Aeschlimann,Eclipse,...,10,10/19/2001 13:41,Windows 2000,P1,darin.eclipse,Darin Wright,normal,---,2,0
4,5820,JDT,UI,aeschli,VERIFIED,FIXED,Close all editors brings up hierarchy of object,11/20/2001 16:22,Martin Aeschlimann,Eclipse,...,5,11/12/2001 18:18,Windows 2000,P1,jed.anderson,Jed Anderson,normal,---,2,0

In [19]:
# column names - for self
eclipse_df.columns

Index(['Bug\nID', 'Product', 'Component', 'Assignee', 'Status', 'Resolution',
       'Summary', 'Changed', 'Assignee\nReal\nName', 'Classification',
       'Hardware', 'Number of\nComments', 'Opened', 'OS', 'Priority',
       'Reporter', 'Reporter\nReal\nName', 'Severity', 'Target\nMilestone',
       'Version', 'Votes'],
      dtype='object')

In [20]:
# data types - for self
eclipse_df.dtypes

Bug\nID                  int64
Product                 object
Component               object
Assignee                object
Status                  object
Resolution              object
Summary                 object
Changed                 object
Assignee\nReal\nName    object
Classification          object
Hardware                object
Number of\nComments      int64
Opened                  object
OS                      object
Priority                object
Reporter                object
Reporter\nReal\nName    object
Severity                object
Target\nMilestone       object
Version                 object
Votes                    int64
dtype: object

In [47]:
# Finding the average number of comments per bug

# Original Code
# Error 3: name of column included a coded break
#average_comments = eclipse_df["Number of Comments"].mean()
#average_comments


# Couldn't find any data when original was run
# Found by listing columns using eclipse_df.columns
# Comments label included a line break
average_comments = eclipse_df["Number of\nComments"].mean()
average_comments

8.75

In [66]:
# Grouping the DataFrame by "Assignee"

# Original Code
# Error 4: missing open brackets around label
# assignee_group = eclipse_df.groupby("Assignee")

# Solution - added brackets
assignee_group = eclipse_df.groupby(["Assignee"])
#assignee_group.count().head()

# Count how many of each component Assignees worked on and create DataFrame

# Original Code
# Error 5: was nesting dataframe within groupby
#assignee_work = pd.DataFrame(assignee_group["Component"].value_counts())
#assignee_work.head()

# Solution - remove pd.Dataframe to create a series called "assignee_work (series)"
assignee_work_series=assignee_group["Component"].value_counts()
#assignee_work.head()
# then convert into dataframe
assignee_work=assignee_work_series.to_frame()
assignee_work.head(10)

                                Component
Assignee       Component
Aaron_Ferguson UI                      10
Adam_Schlegel  UI                       7
ChrisAustin    User Assistance          3
Claude_Knaus   UI                      31
               Text                     7
Curtis_Windatt UI                       3
               Debug                    2
               API Tools                1
Darin_Swanson  Debug                  264
               Ant                     33

In [67]:
# Rename the "Component" column to "Component Bug Count"

assignee_work=assignee_work.rename(columns={"Component":"Component Bug Count"})
assignee_work.head()

                                Component Bug Count
Assignee       Component
Aaron_Ferguson UI                                10
Adam_Schlegel  UI                                 7
ChrisAustin    User Assistance                    3
Claude_Knaus   UI                                31
               Text                               7

In [68]:
assignee_group.count().head()

,Bug ID,Product,Component,Status,Resolution,Summary,Changed,Assignee Real Name,Classification,Hardware,Number of Comments,Opened,OS,Priority,Reporter,Reporter Real Name,Severity,Target Milestone,Version,Votes
Assignee,,,,,,,,,,,,,,,,,,,,
Aaron_Ferguson,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Adam_Schlegel,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
ChrisAustin,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Claude_Knaus,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38
Curtis_Windatt,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6

In [87]:
eclipse_df.count()

Bug\nID                 10000
Product                 10000
Component               10000
Assignee                10000
Status                  10000
Resolution              10000
Summary                 10000
Changed                 10000
Assignee\nReal\nName    10000
Classification          10000
Hardware                10000
Number of\nComments     10000
Opened                  10000
OS                      10000
Priority                10000
Reporter                10000
Reporter\nReal\nName     9967
Severity                10000
Target\nMilestone       10000
Version                 10000
Votes                   10000
dtype: int64

In [90]:
# Find the percentage of bugs overall fixed by each Assignee

# Original Code
# Error 6: variables not counting what they should be
# total bugs is counting the number of bugs/rows per assignee.
#total_bugs = assignee_group["Assignee"].count()
#print(total_bugs)
# bugs per user is counting the number of bugs per assignee PER assignee
#bugs_per_user = assignee_group["Assignee"].value_counts()
#print(bugs_per_user)

#Error 7: Turning user bug percent into a dataframe rather than a series
#which can then be merged into the data frame
# user_bug_percent = pd.DataFrame((bugs_per_user/total_bugs)*100)
# user_bug_percent.head()

# Solution
# total bugs should count unique bug ID's from the original csv
total_bugs=eclipse_df["Bug\nID"].count()
# print(total_bugs)
# bugs per user should count the total bugs per assignee 
# (what was total bugs in the original code)
bugs_per_user = assignee_group["Assignee"].count()
#print(bugs_per_user)

# user_bug_percent = pd.DataFrame((bugs_per_user/total_bugs)*100)
# user_bug_percent.head()

Assignee
Aaron_Ferguson          10
Adam_Schlegel            7
ChrisAustin              3
Claude_Knaus            38
Curtis_Windatt           6
Darin_Swanson          297
James_Moody              2
Karice_McIntyre          4
Kevin_McGuire            6
Lars.Vogel               3
Michael_Rennie          37
Mike_Wilson              2
Olivier_Thomann         25
Platform-UI-Inbox        4
Randy_Giffen             8
Silenio_Quarti          11
Szymon.Brandys          16
Tod_Creasey            459
Vikas.Chandra            3
a.aswani                 2
abhishek.kishore         8
abuzila                  1
achilles-86              1
achim.demelt             1
aclement                 6
aeschli                627
aferrazz                 1
agarcher                23
ahunter.eclipse          3
aiproulx                 1
                      ...
rafael.oliveira          1
raksha.vasisht          16
rthakkar                 5
ryan_cooper             10
sarika.sinha             1
sasikanth.bharadwaj      1
satyam.kandula           1
serge                    1
silvio_boehler           1
simon_arsenault          6
snorthov                 2
sonia_dimitrov           2
sravankumarl             1
srikanth_sankaran        2
stderr                   1
stephan.herrmann         4
susan                    9
sxenos                  42
szymon.ptaszkiewicz      2
t.s.maeder              13
teicher-bugzilla         3
till_bay                21
tobias_widmer           38
tom.schindl              1
tomasz.zarna             9
unknown                  2
valentam                30
veronika_irvine          2
wassim.melhem            4
zhiyongl                 1
Name: Assignee, Length: 205, dtype: int64

In [ ]:
# Merge the "Percent of Total Bugs Assigned" into the DataFrame
assignee_work = assignee_work.merge(user_bug_percent, on="Assignee")

# Remove the extra columns
assignee_work = assignee_work[[
    "Assignee", "Percent of Total Bugs", "Component", "Component Bug Count"]]
assignee_work.head()